Improvement: Conditions serverside
Ben987/Bondage-Club-Server pull request #61
Opened 2021-01-13 15:24 UTC by SandrineBC

# Summary
These are the server side changes, complementing the PR #1885 on the Bondage-Club client. 
It adds the new 'Conditions' to the server roundtrips and adds it to the mongoDB

# Testing
I tested this on my local installation and - as only existing server calls are used - all worked smoothly.

2021-01-27 20:09 UTC, elliesec requested changes

2021-01-27 20:09 UTC, elliesec commented on app.js
> +							Database.collection("Accounts").updateOne(
This doesn't appear to be updating the DB properly - logging out and back in loses the player's conditions. Have a look at the [MongoDB Node driver docs](http://mongodb.github.io/node-mongodb-native/3.6/api/Collection.html#updateOne) - it looks like you're passing in `{ $set: {Conditions: data.Conditions } }` as the `options` argument. You probably want something like this (I've not tested this yet):
```js
Database.collection("Accounts").updateOne(
    {AccountName: Acc.ChatRoom.Account[A].AccountName },
    { $set: { Appearance: data.Appearance, Conditions: data.Conditions } },
    function (err, res) { if (err) throw err; });
```

2021-01-27 20:19 UTC, elliesec commented on app.js
> +							Database.collection("Accounts").updateOne(
Actually, on further investigation, it doesn't seem to be this specifically, but _something_ is resetting the conditions on relog - I assume that's not intentional?

2021-01-27 20:51 UTC, elliesec commented on app.js
> +							Database.collection("Accounts").updateOne(
Ignore me - I think I get it now.

2022-08-06 18:41 UTC, Ben987 commented
Clean-up of the GitHub pull requests.

2022-08-06 18:41 UTC, closed without merging